service: donat-api

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-west-2

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-west-2:*:*"

functions:
  widget-create:
    handler: widget-create.main
    events:
      - http:
          path: widgets
          method: post
          cors: true
          authorizer:
            arn: "arn:aws:cognito-idp:us-west-2:711668821345:userpool/us-west-2_gRKodqIkn"

  widget-get:
    handler: widget-get.main
    events:
      - http:
          path: widgets/{id}
          method: get
          cors: true

  widget-list:
    handler: widget-list.main
    events:
      - http:
          path: widgets
          method: get
          cors: true
          authorizer:
            arn: "arn:aws:cognito-idp:us-west-2:711668821345:userpool/us-west-2_gRKodqIkn"

  widget-update:
    handler: widget-update.main
    events:
      - http:
          path: widgets/{id}
          method: put
          cors: true
          authorizer:
            arn: "arn:aws:cognito-idp:us-west-2:711668821345:userpool/us-west-2_gRKodqIkn"

  widget-delete:
    handler: widget-delete.main
    events:
      - http:
          path: widgets/{id}
          method: delete
          cors: true
          authorizer:
            arn: "arn:aws:cognito-idp:us-west-2:711668821345:userpool/us-west-2_gRKodqIkn"

  page-create:
    handler: page-create.main
    events:
      - http:
          path: pages
          method: post
          cors: true
          authorizer:
            arn: "arn:aws:cognito-idp:us-west-2:711668821345:userpool/us-west-2_gRKodqIkn"

  page-get:
    handler: page-get.main
    events:
      - http:
          path: pages/{id}
          method: get
          cors: true
          authorizer:
            arn: "arn:aws:cognito-idp:us-west-2:711668821345:userpool/us-west-2_gRKodqIkn"

  page-list:
    handler: page-list.main
    events:
      - http:
          path: pages
          method: get
          cors: true
          authorizer:
            arn: "arn:aws:cognito-idp:us-west-2:711668821345:userpool/us-west-2_gRKodqIkn"

  page-update:
    handler: page-update.main
    events:
      - http:
          path: pages/{id}
          method: put
          cors: true
          authorizer:
            arn: "arn:aws:cognito-idp:us-west-2:711668821345:userpool/us-west-2_gRKodqIkn"

  page-delete:
    handler: page-delete.main
    events:
      - http:
          path: pages/{id}
          method: delete
          cors: true
          authorizer:
            arn: "arn:aws:cognito-idp:us-west-2:711668821345:userpool/us-west-2_gRKodqIkn"

  auth:
    handler: auth.main
    events:
      - http:
          path: auth
          method: get
          cors: true
          authorizer:
            arn: "arn:aws:cognito-idp:us-west-2:711668821345:userpool/us-west-2_gRKodqIkn"

  auth-callback:
    handler: auth-callback.main
    events:
      - http:
          path: auth/callback
          method: get
          cors: true
          authorizer:
            arn: "arn:aws:cognito-idp:us-west-2:711668821345:userpool/us-west-2_gRKodqIkn"

