service: donat-api

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-west-2

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-west-2:*:*"

functions:
  widget-create:
    handler: widget-create.main
    events:
      - http:
          path: widgets
          method: post
          cors: true

  widget-get:
    handler: widget-get.main
    events:
      - http:
          path: widgets/{id}
          method: get
          cors: true

  widget-list:
    handler: widget-list.main
    events:
      - http:
          path: widgets
          method: get
          cors: true

  widget-update:
    handler: widget-update.main
    events:
      - http:
          path: widgets/{id}
          method: put
          cors: true

  widget-delete:
    handler: widget-delete.main
    events:
      - http:
          path: widgets/{id}
          method: delete
          cors: true

  user-create:
    handler: user-create.main
    events:
      - http:
          path: users
          method: post
          cors: true

  user-get:
    handler: user-get.main
    events:
      - http:
          path: users/{id}
          method: get
          cors: true

  user-update:
    handler: user-update.main
    events:
      - http:
          path: users/{id}
          method: put
          cors: true

